const SET_CURRENT_BEER = 'SET_CURRENT_BEER';
const RESET_BEER = 'RESET_BEER';
const SET_FETCH_ERROR = 'SET_FETCH_ERROR';
const SET_LOADING_STATE = 'SET_LOADING_STATE';
const SET_CURRENT_BREWERY = 'SET_CURRENT_BREWERY';
const RESET_BREWERY = 'RESET_BREWERY';

// TODO second phase
// const ADD_PREVIOUS_VIEWED_BEER = 'ADD_PREVIOUS_VIEWED_BEER';
// const ADD_FAVOURITE_BEER = 'ADD_FAVOURITE_BEER';
// const REMOVE_FAVOURITE_BEER = 'REMOVE_FAVOURITE_BEER';

export {
  SET_CURRENT_BEER,
  RESET_BEER,
  SET_FETCH_ERROR,
  SET_LOADING_STATE,
  SET_CURRENT_BREWERY,
  RESET_BREWERY,
  // ADD_PREVIOUS_VIEWED_BEER,
  // ADD_FAVOURITE_BEER,
  // REMOVE_FAVOURITE_BEER,
};

